---
# Secure MariaDB installation

- name: Check if MariaDB root password is already set
  shell: mysql -u root -e "SELECT 1" 2>/dev/null
  register: mysql_root_access
  failed_when: false
  changed_when: false

- name: Set MariaDB root password (initial setup)
  mysql_user:
    name: root
    host: localhost
    password: "{{ mariadb_root_password }}"
    login_user: root
    login_password: ""
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present
  when: mysql_root_access.rc == 0
  ignore_errors: yes

- name: Set MariaDB root password (alternative method for Docker)
  shell: |
    mysql -u root --skip-password -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('{{ mariadb_root_password }}'); FLUSH PRIVILEGES;" || \
    mysql -u root -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('{{ mariadb_root_password }}'); FLUSH PRIVILEGES;" || \
    mysqladmin -u root password '{{ mariadb_root_password }}'
  when: 
    - mysql_root_access.rc == 0
    - ansible_virtualization_type == 'docker'
  ignore_errors: yes

- name: Set MariaDB root password (alternative method for non-Docker)
  shell: |
    mysql -u root --skip-password -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('{{ mariadb_root_password }}'); FLUSH PRIVILEGES;" || \
    mysql -u root -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('{{ mariadb_root_password }}'); FLUSH PRIVILEGES;" || \
    mysqladmin -u root password '{{ mariadb_root_password }}'
  when: 
    - mysql_root_access.rc == 0
    - ansible_virtualization_type != 'docker'
  ignore_errors: yes

- name: Create /root/.my.cnf with root credentials
  copy:
    content: |
      [client]
      user=root
      password={{ mariadb_root_password }}
    dest: /root/.my.cnf
    mode: '0600'

- name: Remove anonymous MySQL users
  mysql_user:
    name: ""
    host_all: yes
    state: absent
    login_user: root
    login_password: "{{ mariadb_root_password }}"

- name: Remove test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mariadb_root_password }}"

- name: Remove privileges on test database
  mysql_query:
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    query: "DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'"

- name: Flush privileges
  mysql_query:
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    query: "FLUSH PRIVILEGES"



